### ISSUE TITLE
Interoperability issue with payeezyjs/OPC when freecharger is the payment method

### ISSUE THREAD

**Issue by lat9** [zencart/payeezyjs#4]
If a store uses both the Payeezyjs payment method and the One-Page Checkout plugin, there's an interoperability issue if a 0-price product (e.g. **_A Free Product - All_**, /index.php?main_page=product_info&cPath=24&products_id=57) is the cart's only product, normally kicking in the `freecharger` payment method.

The jscript_payeezy.php file (copied to the /includes/modules/pages/checkout_one directory) gets loaded and, since there's no payeezy payment method active, causes a jQuery error resulting in the checkout hanging.

I was able to correct the integration issue by editing that module, adding the second clause below:
```php
if ($payment_modules->in_special_checkout() || !defined(MODULE_PAYMENT_PAYEEZYJSZC_STATUS) || MODULE_PAYMENT_PAYEEZYJSZC_STATUS != 'True' || (!defined('MODULE_PAYMENT_PAYEEZYJSZC_JSSECURITY_KEY') && !defined('MODULE_PAYMENT_PAYEEZYJSZC_JSSECURITY_KEY_SANDBOX') )) {
    return false;
}
if (isset($payment_modules->paymentClass) && $payment_modules->paymentClass->code != 'payeezyjszc') {
    return false;
}
```

**Update**:  Like similar comments for the Square payment method, the change needs to be made at the jQuery level -- otherwise, a customer can't change their mind and use Payeezyjs after selecting another payment method and returning to `checkout_payment` from the `checkout_confirmation` page.

**Comment by drbyte** [comment]
Good catch. A PR is welcome.

**Comment by lat9** [comment]
Should I submit the change both here and to the zc156 repository, or is it sufficient to submit the PR here only?

Noting that the issue also raises itself when the payment method is zone-restricted and the current billing zone is not within the payment-method's configured value.

**Comment by drbyte** [comment]
> Should I submit the change both here and to the zc156 repository, or is it sufficient to submit the PR here only?

I'll merge it into v156

> Noting that the issue also raises itself when the payment method is zone-restricted and the current billing zone is not within the payment-method's configured value.

Are you saying that's another issue that needs addressing beyond the fix you submitted?

**Comment by lat9** [comment]
> Are you saying that's another issue that needs addressing beyond the fix you submitted?

Nope, just identifying other symptoms that were corrected.
